# Generated by Django 2.2.6 on 2019-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnergroup',
            name='partners',
            field=models.ManyToManyField(null=True, related_name='partnergroups', to='partner.Partner'),
        ),
    ]
