# Generated by Django 2.2.6 on 2019-12-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_group', '0002_auto_20191208_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnergroup',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partnergroups', to='partner.Partner'),
        ),
    ]
