# Generated by Django 2.2.6 on 2019-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_group', '0004_auto_20191208_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnergroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='size_1',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='size_2',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='size_3',
            field=models.IntegerField(default=2),
        ),
    ]
