# Generated by Django 2.2.6 on 2019-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_group', '0005_auto_20191208_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnergroup',
            name='size_2',
            field=models.IntegerField(default=3),
        ),
    ]
