# Generated by Django 2.2.6 on 2019-12-03 16:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_auto_20191001_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to=''),
        ),
    ]
