# Generated by Django 2.2.3 on 2019-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('tickets_link', models.URLField(blank=True)),
            ],
        ),
    ]
