# Generated by Django 2.2.6 on 2019-12-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
