# Generated by Django 2.2.6 on 2019-12-08 13:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
